base = "/empty-fork"

[sitenavlinks.Home]
title = "Home"
url = "/"

[sitenavlinks.About]
title = "About"
url = "/about/index.html"

[sitenavlinks.About.subnav.team]
title = "The team"
url = "/about/team.html"

[sitenavlinks.About.subnav.studio]
title = "Our studio"
url = "/about/studio.html"
